language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
services:
  - redis-server
before_install:
  - redis-server tests/sentinel.conf --sentinel
install:
  - python setup.py install
script: nosetests
